source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.2'

gem 'rails',     '6.1.7'
gem 'puma',      '5.1.1'
gem 'bootsnap',  '1.15.0', require: false
gem 'rack-cors'
gem 'pg',        '1.1.4'
gem 'faker',     '2.15.1'
gem 'active_model_serializers', '0.10.12'
gem 'bcrypt', '3.1.16'
gem "rails_same_site_cookie", '0.1.8'
gem "aws-sdk-s3", require: false
gem "pg_search",  '2.3.5'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'awesome_print',         '1.8.0'
  gem 'listen',                '3.4.1'
  gem 'spring'
  gem 'spring-watcher-listen', '2.0.1'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
# gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]